// <auto-generated />
namespace ERPProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateEmployeeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateEmployeeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201602211850042_updateEmployeeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
