// <auto-generated />
namespace ERPProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateGenderColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateGenderColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201602191739368_updateGenderColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
